### ISSUE TITLE
unexpected hmm results

### ISSUE THREAD

**Issue by JIAOYIING** [joshuacnf/Ctrl-G#6]
Hi, 

Thanks for sharing your code.

In my understanding, hmm_logits, hmm_logits_ are log(p(Sn ∈ F, xt, x<t)) and log(p(xt, x<t)). I tried to torch.exp and divide them to get p(α | xt, x<t) but found some result values are >1.

I would appreciate it if you could point out my misunderstandings or explain this.

**Comment by joshuacnf** [comment]
p(Sn ∈ F, xt, x<t) and p(xt, x<t) are extremely close to 0 so we need to work in the log space: have you tried computing torch.exp(hmm_logits - hmm_logits_)?

**Comment by JIAOYIING** [comment]
yes, max element in torch.exp(hmm_logits - hmm_logits_) could be 21.6307. does this implies p(Sn ∈ F, xt, x<t) > p(xt, x<t)?

**Comment by joshuacnf** [comment]
can you provide the code for reproducing this bug? As you've mentioned p(Sn ∈ F, xt, x<t) > p(xt, x<t) should not happen

**Comment by JIAOYIING** [comment]
in ctrlg/utils.py:
            hmm_batch_size = len(selected_idx) if self.hmm_batch_size is None else min(len(selected_idx), self.hmm_batch_size)
            hmm_logits, hmm_logits_ = self.compute_logits(selected_prefixes, selected_token_ranges, hmm_batch_size)
            # hmm_logits -= hmm_logits_
            log_div = hmm_logits - hmm_logits_
            if not torch.all((log_div < 0)):
                print(f'exist log_div >= 0 {torch.max(log_div)}')
            prob_div = torch.exp(hmm_logits-hmm_logits_)
            if not torch.all((prob_div >= 0) & (prob_div <= 1)):
                print(f'exist prob_div > 1 {torch.max(prob_div)}')
                
example output:
exist log_div >= 0 3.0741119384765625
exist prob_div > 1 21.630664825439453

**Comment by joshuacnf** [comment]
can you also provide the DFA applied and specify the hmm checkpoint you're using? as well as the the value of the selected_prefixes, selected_token_ranges.

**Comment by JIAOYIING** [comment]
I am using hmm_gpt2-large_common-gen_4096 checkpoint. Logic constraints are example constraints 1 in tutorial_ctrlg.ipynb. The rest codes are cloned from this repo without modification.

I am using a smaller batch size 8 to fit my laptop. The issue of torch.exp(hmm_logits - hmm_logits_) > 1 appears starting after generating 6 tokens and also in the following generation steps.
e.g.
selected_prefixes:[(317, 582, 318, 10311, 257, 7161), (317, 582, 318, 5586, 319, 257), (257, 582, 318, 10311, 257, 7161), (317, 2415, 318, 5586, 319, 257), (317, 582, 318, 6155, 866, 262), (317, 582, 290, 2415, 389, 6155), (317, 582, 318, 5586, 319, 262), (317, 582, 290, 2415, 389, 10311)]
selected_token_ranges: [[5, 32], [5, 32], [5, 32], [5, 32], [5, 32], [5, 32], [5, 32], [5, 32]]
exist log_div >= 0 0.7370796203613281
exist prob_div > 1 2.0898237228393555

**Comment by joshuacnf** [comment]
Thank you for the information. I've looked into this case and found that there is indeed overcounting happening here when computing the conditional probabilities. 

A quick fix would be to change `suffix = '<|endoftext|>'` to `suffix = ' <|endoftext|>'` or `suffix = '.<|endoftext|>'` in step 2 (notice the extra space/period here).

The underlying reason is that our implementation assumes that for the LLM distribution, an `<eos>` token is always followed by an `<eos>` token thus we can rely on the fact that the suffix is non-empty (in addition to the `<eos>` token) to generate outputs of different length without overcounting.

Thank you for identifying this bug and I will quickly fix the tutorial notebook.

Please let me know whether this fix works for you.

**Comment by JIAOYIING** [comment]
Thanks for providing the fix. It works for me.
Seems the number of generated words constraint is also important for avoiding overcounting. If I remove this constraint or change the range (e.g. a=8, b=12), p(Sn ∈ F, xt, x<t) / p(xt, x<t) could also be larger than 1. Could you suggest a safe range for this word number constraint?
Besides, it seems hmm_gpt2-large_common-gen_4096 is trained with sentences of length 32. I think it cannot model distributions of longer sequences. In the token length section of the tutorials, all the max new tokens is set to 32 but in some cases the prefix and sufix are not empty. Can you explain why it works for sequences longer than 32? And what is the longest possible sequence I could generate?

**Comment by joshuacnf** [comment]
The word count constraint should not result in overcounting (prob > 1), as long as the suffix is non-empty. Is this problem happening again for example constraint 2? Please let me know.

The word count constraint should be bounded by max_tokens: you cannot have more words than the maximum number of tokens.

Even though HMMs are trained on sequences of length 32 (or 64) they should generalize to longer sequences as the transition and emission matrices are independent of position t.

**Comment by JIAOYIING** [comment]
1. For the word count constraint, when using most constraints from example 1 and just changing the range of a, b:
prefix = ''
prompt = '<|endoftext|>'
suffix = '.<|endoftext|>' 
keyphrases = [[' riding a bike', ' ride bikes', ' rides a bike', ' biking', ' bikes'],
            [' park', ' beach']]
a, b = 8, 12
selected_prefixs: [(317, 582, 290, 2415, 389, 5586, 319, 257, 7624), (317, 1862, 2933, 318, 2712, 351, 257, 13373, 13), (317, 582, 290, 257, 2415, 1650, 319, 257, 7624), (317, 582, 290, 257, 2415, 389, 5586, 319, 257), (317, 582, 290, 2415, 389, 6155, 866, 262, 4675), (317, 582, 290, 257, 2415, 389, 6155, 866, 257), (317, 582, 290, 257, 2415, 389, 6155, 866, 262), (317, 582, 290, 2415, 389, 6155, 866, 257, 4675)]
selected_range: [[5, 32], [5, 32], [5, 32], [5, 32], [5, 32], [5, 32], [5, 32], [5, 32]]
exist prob_div > 1 1.0000019073486328

2. For generating longer sequences, though the matrices are not dependent on t, it doesn't seem generalizable to longer sequences. when changing example 1 a, b = 50, 50, max_new_token=64, the best generation results:
A man and a woman are sitting on a bench in a park. The woman is wearing a red dress and the man is wearing a blue dress and hat.             A man and a woman are sitting on a bench in a park and the woman is wearing red dress.
It tends to end generate at ~32, after that the information is repeated

**Comment by joshuacnf** [comment]
1. Having a probability value of 1.0000019073486328 is more likely due to numerical errors so it shouldn't be a problem.

2. For the CommonGen experiments, since both GPT2-large and the HMM checkpoints are domain adapted, they wouldn't be able to generate fluent long sentences. The TULU2-7B model is less constrained and should be able to generalize better.

**Comment by JIAOYIING** [comment]
Make sense! Thanks a lot for your responses.
